server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients: ["MUSIC", "ANDROID", "WEB"]
  lavasrc:
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: false
    lyrics-sources:
      spotify: true
      deezer: false
      youtube: true
    spotify:
      clientId: "3c03861900024f06bbb4d4d8d12d9555"
      clientSecret: "753dd72db0a94b638113901d9a451adb"
      spDc: "AQDbk3nOmMCiEnGfFq_buFnrkTmlNOuLIBePhWUbulrOnawdDRj-duREhWkqsqh1ie0Mi9i5FXJjP_FobUsKL_CxUBsnXpM9BuWA-DJ-LHnDtwyq2rT9sP3nO7Bg1iou13emtz_wDISIX--0LxBE70vzRqxgdmShe2kelmqBTslyhQo-_KDbs_UmQVp8x3xufTLvP6zNSF7y0DfmbR35P6zPPkI-"
      countryCode: "US"
      playlistLoadLimit: 10
      albumLoadLimit: 10
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.2.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.1.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "FTRKYkoRw@5$EXkcdD#!ol52"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false 
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30